const punctuation = [
  "'",
  '?',
  '*',
  '<',
  '>',
  '&',
  '(',
  ')',
  '{',
  '}',
  '[',
  ']',
  "'",
  '.',
  ',',
  '–',
  '@',
  '#',
  '_',
  '‒',
  '%',
  '^',
  '!',
  ':',
];

enum BlockTag {
  ADDRESS = 'address',
  ARTICLE = 'article',
  ASIDE = 'aside',
  BLOCKQUOTE = 'blockquote',
  CANVAS = 'canvas',
  DD = 'dd',
  DIV = 'div',
  DL = 'dl',
  DT = 'dt',
  FIELDSET = 'fieldset',
  FIGCAPTION = 'figcaption',
  FIGURE = 'figure',
  FOOTER = 'footer',
  FORM = 'form',
  H1 = 'h1',
  H6 = 'h6',
  HEADER = 'header',
  HR = 'hr',
  LI = 'li',
  MAIN = 'main',
  NAV = 'nav',
  NOSCRIPT = 'noscript',
  OL = 'ol',
  P = 'p',
  PRE = 'pre',
  SECTION = 'section',
  TABLE = 'table',
  TFOOT = 'tfoot',
  UL = 'ul',
  VIDEO = 'video',
}

enum DOMPurifyAllowedTag {
  A = 'a',
  ABBR = 'abbr',
  ACRONYM = 'acronym',
  ADDRESS = 'address',
  AREA = 'area',
  ARTICLE = 'article',
  ASIDE = 'aside',
  AUDIO = 'audio',
  B = 'b',
  BDI = 'bdi',
  BDO = 'bdo',
  BIG = 'big',
  BLINK = 'blink',
  BLOCKQUOTE = 'blockquote',
  BODY = 'body',
  BR = 'br',
  BUTTON = 'button',
  CANVAS = 'canvas',
  CAPTION = 'caption',
  CENTER = 'center',
  CITE = 'cite',
  CODE = 'code',
  COL = 'col',
  COLGROUP = 'colgroup',
  CONTENT = 'content',
  DATA = 'data',
  DATALIST = 'datalist',
  DD = 'dd',
  DECORATOR = 'decorator',
  DEL = 'del',
  DETAILS = 'details',
  DFN = 'dfn',
  DIR = 'dir',
  DIV = 'div',
  DL = 'dl',
  DT = 'dt',
  ELEMENT = 'element',
  EM = 'em',
  FIELDSET = 'fieldset',
  FIGCAPTION = 'figcaption',
  FIGURE = 'figure',
  FONT = 'font',
  FOOTER = 'footer',
  FORM = 'form',
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  H5 = 'h5',
  H6 = 'h6',
  HEAD = 'head',
  HEADER = 'header',
  HGROUP = 'hgroup',
  HR = 'hr',
  HTML = 'html',
  I = 'i',
  IMG = 'img',
  INPUT = 'input',
  INS = 'ins',
  KBD = 'kbd',
  LABEL = 'label',
  LEGEND = 'legend',
  LI = 'li',
  MAIN = 'main',
  MAP = 'map',
  MARK = 'mark',
  MARQUEE = 'marquee',
  MENU = 'menu',
  MENUITEM = 'menuitem',
  METER = 'meter',
  NAV = 'nav',
  NOBR = 'nobr',
  OL = 'ol',
  OPTGROUP = 'optgroup',
  OPTION = 'option',
  OUTPUT = 'output',
  P = 'p',
  PRE = 'pre',
  PROGRESS = 'progress',
  Q = 'q',
  RP = 'rp',
  RT = 'rt',
  RUBY = 'ruby',
  S = 's',
  SAMP = 'samp',
  SECTION = 'section',
  SELECT = 'select',
  SHADOW = 'shadow',
  SMALL = 'small',
  SOURCE = 'source',
  SPACER = 'spacer',
  SPAN = 'span',
  STRIKE = 'strike',
  STRONG = 'strong',
  STYLE = 'style',
  SUB = 'sub',
  SUMMARY = 'summary',
  SUP = 'sup',
  TABLE = 'table',
  TBODY = 'tbody',
  TD = 'td',
  TEMPLATE = 'template',
  TEXTAREA = 'textarea',
  TFOOT = 'tfoot',
  TH = 'th',
  THEAD = 'thead',
  TIME = 'time',
  TR = 'tr',
  TRACK = 'track',
  TT = 'tt',
  U = 'u',
  UL = 'ul',
  VAR = 'var',
  VIDEO = 'video',
  WBR = 'wbr',
}

// // test with apple
// enum FontFamilyEnum {
//   ARIAL = 'Arial',
//   COURIER_NEW = 'Courier New',
//   FUTURA = 'Futura',
//   // GILL_SANS = 'Gill Sans',
//   HELVETICA = 'Helvetica',
//   LUCIDA_GRANDE = 'Lucida Grande',
//   MENLO = 'Menlo',
//   MONACO = 'Monaco',
//   MONOSPACE = 'Monospace',
//   PALATINO = 'Palatino',
//   SANS_SERIF = 'sans-serif',
//   SYMBOL = 'Symbol',
//   SYSTEM_UI = 'system-ui',
//   TIMES_NEW_ROMAN = 'Times New Roman',
//   TREBUCHET_MS = 'Trebuchet MS',
//   UI_MONOSPACE = 'ui-monospace',
//   UI_ROUNDED = 'ui-rounded',
//   UI_SANS_SERIF = 'ui-sans-serif',
//   VERDANA = 'Verdana',
// }

enum FontFamilyEnum {
  COURIER_NEW = 'Courier New',
  MONACO = 'Monaco',
  MONOSPACE = 'Monospace',
  PALATINO = 'Palatino',
  TIMES_NEW_ROMAN = 'Times New Roman',
  VERDANA = 'Verdana',
}

enum TextAlignEnum {
  START = 'start',
  JUSTIFY = 'justify',
}

type FontFamily = `${FontFamilyEnum}`;

type TextAlign = `${TextAlignEnum}`;

export type { FontFamily, TextAlign };

export {
  BlockTag,
  DOMPurifyAllowedTag,
  FontFamilyEnum,
  punctuation,
  TextAlignEnum,
};
